CREATE TABLE u_db (
	u_num INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	u_name CHAR(16) NOT NULL,
	u_age INT NOT NULL,
	u_gender INT NOT NULL,
	u_job VARCHAR(16) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;