CREATE TABLE u_db (
	u_num INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	u_name VARCHAR(80) NOT NULL,
	u_age INT NOT NULL,
	u_gender INT NOT NULL,
	u_job VARCHAR(80) NOT NULL,
    	u_bathing INT NOT NULL DEFAULT '0',
    	u_water INT NOT NULL DEFAULT '0',
    	u_temperature INT NOT NULL DEFAULT '0',
    	u_time INT NOT NULL DEFAULT '0',
    	u_last TINYINT NOT NULL DEFAULT '0'
);
